# Generated by Django 5.0.1 on 2025-04-06 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photolink', models.CharField(max_length=255, verbose_name='Фотография')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
                ('grams', models.CharField(max_length=50, verbose_name='Граммы')),
                ('kalories', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Калории')),
                ('protein', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Белки')),
                ('fat', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Жиры')),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Углеводы')),
                ('structure', models.CharField(max_length=255, verbose_name='Состав')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступен для заказа')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новое')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хит')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='Категория')),
            ],
        ),
    ]
