# Generated by Django 5.0.1 on 2025-04-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dishes_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default='123', max_length=100, verbose_name='Класс иконки font-awesome'),
        ),
    ]
