# Generated by Django 5.0.1 on 2025-05-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='dish',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
