# Generated by Django 5.0.1 on 2025-05-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='sequence_number',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
        ),
    ]
